name: L

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm
          restore-keys: npm

      - name: Cache Playwright Chromium
        uses: actions/cache@v4
        with:
          path: 'C:\Users\runneradmin\AppData\Local\ms-playwright\'
          key: playwright
          restore-keys: playwright

      - name: Install dependencies
        run: |
          npm install playwright playwright-extra puppeteer-extra-plugin-stealth
          npx playwright install chromium

      - name: Run screenshot script
        run: node index.js
